# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-10 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phoneno',
            field=models.BigIntegerField(),
        ),
    ]
