# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-18 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_accuracymodel3'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakerealmodel',
            name='alpha',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
