# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-03-06 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_fakerealmodel_alpha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
