# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsid', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
