# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='label',
            field=models.CharField(max_length=100000000),
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='text',
            field=models.CharField(max_length=100000000),
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='title',
            field=models.CharField(max_length=20000000),
        ),
    ]
